export const ON_APP_LOAD = 'login/ON_APP_LOAD';

export const LOGIN_LOAD = 'login/LOGIN_LOAD';
export const LOGIN_SUCCESS = 'login/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'login/LOGIN_FAIL';

export const RESET_PASSWORD_LOAD = 'login/RESET_PASSWORD_LOAD';
export const RESET_PASSWORD_SUCCESS = 'login/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'login/RESET_PASSWORD_FAIL';

export const UPDATE_PASSWORD_LOAD = 'login/UPDATE_PASSWORD_LOAD';
export const UPDATE_PASSWORD_SUCCESS = 'login/UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'login/UPDATE_PASSWORD_FAIL';
