export const CREATE_TEAM_MEMBER_LOAD = 'teamMembers/CREATE_TEAM_MEMBER_LOAD';
export const CREATE_TEAM_MEMBER_SUCCESS = 'teamMembers/CREATE_TEAM_MEMBER_SUCCESS';
export const CREATE_TEAM_MEMBER_FAILURE = 'teamMembers/CREATE_TEAM_MEMBER_FAIL';

export const CREATE_TEAM_HEAD_LOAD = 'teamMembers/CREATE_TEAM_HEAD_LOAD';
export const CREATE_TEAM_HEAD_SUCCESS = 'teamMembers/CREATE_TEAM_HEAD_SUCCESS';
export const CREATE_TEAM_HEAD_FAILURE = 'teamMembers/CREATE_TEAM_HEAD_FAILURE';

export const GET_TEAM_MEMBERS_LOAD = 'teamMembers/GET_TEAM_MEMBERS_LOAD';
export const GET_TEAM_MEMBERS_SUCCESS = 'teamMembers/GET_TEAM_MEMBERS_SUCCESS';
export const GET_TEAM_MEMBERS_FAILURE = 'teamMembers/GET_TEAM_MEMBERS_FAILURE';

export const EDIT_TEAM_MEMBER_LOAD = 'teamMembers/EDIT_TEAM_MEMBER_LOAD';
export const EDIT_TEAM_MEMBER_SUCCESS = 'teamMembers/EDIT_TEAM_MEMBER_SUCCESS';
export const EDIT_TEAM_MEMBER_FAILURE = 'teamMembers/EDIT_TEAM_MEMBER_FAILURE';

export const EDIT_TEAM_HEAD_LOAD = 'teamMembers/EDIT_TEAM_HEAD_LOAD';
export const EDIT_TEAM_HEAD_SUCCESS = 'teamMembers/EDIT_TEAM_HEAD_SUCCESS';
export const EDIT_TEAM_HEAD_FAILURE = 'teamMembers/EDIT_TEAM_HEAD_FAILURE';

export const SEND_CRENDENTIAL_LOAD = 'teamMembers/SEND_CRENDENTIAL_LOAD';
export const SEND_CRENDENTIAL_SUCCESS = 'teamMembers/SEND_CRENDENTIAL_SUCCESS';
export const SEND_CRENDENTIAL_FAILURE = 'teamMembers/SEND_CRENDENTIAL_FAILURE';

export const RESEND_CRENDENTIAL_LOAD = 'teamMembers/RESEND_CRENDENTIAL_LOAD';
export const RESEND_CRENDENTIAL_SUCCESS = 'teamMembers/RESEND_CRENDENTIAL_SUCCESS';
export const RESEND_CRENDENTIAL_FAILURE = 'teamMembers/RESEND_CRENDENTIAL_FAILURE';

export const DIRECT_REPORTING_LOAD = 'teamMembers/DIRECT_REPORTING_LOAD';
export const DIRECT_REPORTING_SUCCESS = 'teamMembers/DIRECT_REPORTING_SUCCESS';
export const DIRECT_REPORTING_FAILURE = 'teamMembers/DIRECT_REPORTING_FAILURE';

export const DELETE_TEAM_MEMBER_LOAD = 'teamMembers/DELETE_TEAM_MEMBER_LOAD';
export const DELETE_TEAM_MEMBER_SUCCESS = 'teamMembers/DELETE_TEAM_MEMBER_SUCCESS';
export const DELETE_TEAM_MEMBER_FAILURE = 'teamMembers/DELETE_TEAM_MEMBER_FAILURE';

