export const LEAD_MONTHLY_SUMMARY_LOAD = 'homeDashboard/LEAD_MONTHLY_SUMMARY_LOAD';
export const LEAD_MONTHLY_SUMMARY_SUCCESS = 'homeDashboard/LEAD_MONTHLY_SUMMARY_SUCCESS';
export const LEAD_MONTHLY_SUMMARY_FAIL = 'homeDashboard/LEAD_MONTHLY_SUMMARY_FAIL';

export const TEAM_PERFORMANCE_LOAD = 'homeDashboard/TEAM_PERFORMANCE_LOAD';
export const TEAM_PERFORMANCE_SUCCESS = 'homeDashboard/TEAM_PERFORMANCE_SUCCESS';
export const TEAM_PERFORMANCE_FAIL = 'homeDashboard/TEAM_PERFORMANCE_FAIL';
