export const CREATEEXCHANGEVEHICLE_LOAD = 'financeOnboarding/CREATEEXCHANGEVEHICLE_LOAD';
export const CREATEEXCHANGEVEHICLE_SUCCESS = 'financeOnboarding/CREATEEXCHANGEVEHICLE_SUCCESS';
export const CREATEEXCHANGEVEHICLE_FAIL = 'financeOnboarding/CREATEEXCHANGEVEHICLE_FAIL';

export const GET_EXCHANGEVEHICLE_LOAD = 'financeOnboarding/GET_EXCHANGEVEHICLE_LOAD';
export const GET_EXCHANGEVEHICLE_SUCCESS = 'financeOnboarding/GET_EXCHANGEVEHICLE_SUCCESS';
export const GET_EXCHANGEVEHICLE_FAIL = 'financeOnboarding/GET_EXCHANGEVEHICLE_FAIL';

export const UPDATE_EXCHANGEVEHICLE_LOAD = 'financeOnboarding/UPDATE_EXCHANGEVEHICLE_LOAD';
export const UPDATE_EXCHANGEVEHICLE_SUCCESS = 'financeOnboarding/UPDATE_EXCHANGEVEHICLE_SUCCESS';
export const UPDATE_EXCHANGEVEHICLE_FAIL = 'financeOnboarding/UPDATE_EXCHANGEVEHICLE_FAIL';

export const GET_MANUFACTURER_LIST_LOAD = 'financeOnboarding/GET_MANUFACTURER_LIST_LOAD';
export const GET_MANUFACTURER_LIST_SUCCESS = 'financeOnboarding/GET_MANUFACTURER_LIST_SUCCESS';
export const GET_MANUFACTURER_LIST_FAIL = 'financeOnboarding/GET_MANUFACTURER_LIST_FAIL';

export const GET_EXCHANGE_VEHICLE_LIST_LOAD = 'financeOnboarding/GET_EXCHANGE_VEHICLE_LIST_LOAD';
export const GET_EXCHANGE_VEHICLE_LIST_SUCCESS = 'financeOnboarding/GET_EXCHANGE_VEHICLE_LIST_SUCCESS';
export const GET_EXCHANGE_VEHICLE_LIST_FAIL = 'financeOnboarding/GET_EXCHANGE_VEHICLE_LIST_FAIL';

export const GET_EXCHANGE_VARIANT_LIST_LOAD = 'financeOnboarding/GET_EXCHANGE_VARIANT_LIST_LOAD';
export const GET_EXCHANGE_VARIANT_LIST_SUCCESS = 'financeOnboarding/GET_EXCHANGE_VARIANT_LIST_SUCCESS';
export const GET_EXCHANGE_VARIANT_LIST_FAIL = 'financeOnboarding/GET_EXCHANGE_VARIANT_LIST_FAIL';

export const GET_EXCHANGE_PRICE_LOAD = 'financeOnboarding/GET_EXCHANGE_PRICE_LOAD';
export const GET_EXCHANGE_PRICE_SUCCESS = 'financeOnboarding/GET_EXCHANGE_PRICE_SUCCESS';
export const GET_EXCHANGE_PRICE_FAIL = 'financeOnboarding/GET_EXCHANGE_PRICE_FAIL';
