export const BOOK_TEST_RIDE_LOAD = 'testride/BOOK_TEST_RIDE_LOAD';
export const BOOK_TEST_RIDE_SUCCESS = 'testride/BOOK_TEST_RIDE_SUCCESS';
export const BOOK_TEST_RIDE_FAILURE = 'testride/BOOK_TEST_RIDE_FAILURE';

export const ADD_DOCUMENT_LOAD = 'testride/ADD_DOCUMENT_LOAD';
export const ADD_DOCUMENT_SUCCESS = 'testride/ADD_DOCUMENT_SUCCESS';
export const ADD_DOCUMENT_FAILURE = 'testride/ADD_DOCUMENT_FAILURE';

export const DELETE_DOCUMENT_LOAD = 'testride/DELETE_DOCUMENT_LOAD';
export const DELETE_DOCUMENT_SUCCESS = 'testride/DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILURE = 'testride/DELETE_DOCUMENT_FAILURE';

export const UDPATE_DOCUMENT_LOAD = 'testride/UDPATE_DOCUMENT_LOAD';
export const UPDATE_DOCUMENT_SUCCESS = 'testride/UPDATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_FAILURE = 'testride/UPDATE_DOCUMENT_FAILURE';

export const GET_LEAD_LOAD = 'testride/GET_LEAD_LOAD';
export const GET_LEAD_SUCESS = 'testride/GET_LEAD_SUCESS';
export const GET_LEAD_FAILURE = 'testride/GET_LEAD_FAILURE';

export const GET_TEST_RIDE_COUNT_LOAD = 'testride/GET_TEST_RIDE_COUNT_LOAD';
export const GET_TEST_RIDE_COUNT_SUCCESS = 'testride/GET_TEST_RIDE_COUNT_SUCCESS';
export const GET_TEST_RIDE_COUNT_FAILURE = 'testride/GET_TEST_RIDE_COUNT_FAILURE';

export const GET_TEST_RIDE_DATE = 'testride/GET_TEST_RIDE_DATE';
export const GET_TEST_RIDE_DATE_SUCCESS = 'testride/GET_TEST_RIDE_DATE_SUCCESS';
export const GET_TEST_RIDE_DATE_FAILURE = 'testride/GET_TEST_RIDE_DATE_FAILURE';

export const GET_TEST_RIDE_SLOTS = 'testride/GET_TEST_RIDE_SLOTS';
export const GET_TEST_RIDE_SLOTS_SUCCESS = 'testride/GET_TEST_RIDE_SLOTS_SUCCESS';
export const GET_TEST_RIDE_SLOTS_FAILURE = 'testride/GET_TEST_RIDE_SLOTS_FAILURE';

export const GET_TEST_RIDE_AVAILED_LEADS = 'testride/GET_TEST_RIDE_AVAILED_LEADS_LOAD';
export const GET_TEST_RIDE_AVAILED_LEADS_SUCCESS = 'testride/GET_TEST_RIDE_AVAILED_LEADS_SUCCESS';
export const GET_TEST_RIDE_AVAILED_LEADS_FAILURE = 'testride/GET_TEST_RIDE_AVAILED_LEADS_FAILURE';

export const CLEAR_TEST_RIDE_SLOTS = 'testride/CLEAR_TEST_RIDE_SLOTS';

export const MARK_ALL_VERIFIED_LOAD = 'testride/MARK_ALL_VERIFIED_LOAD';
export const MARK_ALL_VERIFIED_SUCCESS = 'testride/MARK_ALL_VERIFIED_SUCCESS';
export const MARK_ALL_VERIFIED_FAILURE = 'testride/MARK_ALL_VERIFIED_FAILURE';
