export const GET_TEAM_MEMBERS_LOAD = 'leadHistory/GET_TEAM_MEMBERS_LOAD';
export const GET_TEAM_MEMBERS_SUCCESS = 'leadHistory/GET_TEAM_MEMBERS_SUCCESS';
export const GET_TEAM_MEMBERS_FAIL = 'leadHistory/GET_TEAM_MEMBERS_FAIL';

export const GET_ALLVEHICLES_LOAD = 'leadHistory/GET_ALLVEHICLES_LOAD';
export const GET_ALLVEHICLES_SUCCESS = 'leadHistory/GET_ALLVEHICLES_SUCCESS';
export const GET_ALLVEHICLES_FAIL = 'leadHistory/GET_ALLVEHICLES_FAIL';

export const UPDATE_LEADDETAIL_LOAD = 'leadHistory/UPDATE_LEADDETAIL_LOAD';
export const UPDATE_LEADDETAIL_SUCCESS = 'leadHistory/UPDATE_LEADDETAIL_SUCCESS';
export const UPDATE_LEADDETAIL_FAIL = 'leadHistory/UPDATE_LEADDETAIL_FAIL';

export const DELETE_LEADDETAIL_LOAD = 'leadHistory/DELETE_LEADDETAIL_LOAD';
export const DELETE_LEADDETAIL_SUCCESS = 'leadHistory/DELETE_LEADDETAIL_SUCCESS';
export const DELETE_LEADDETAIL_FAIL = 'leadHistory/DELETE_LEADDETAIL_FAIL';

export const UPDATE_LEADDETAIL_STATUS_LOAD = 'leadHistory/UPDATE_LEADDETAIL_STATUS_LOAD';
export const UPDATE_LEADDETAIL_STATUS_SUCCESS = 'leadHistory/UPDATE_LEADDETAIL_STATUS_SUCCESS';
export const UPDATE_LEADDETAIL_STATUS_FAIL = 'leadHistory/UPDATE_LEADDETAIL_STATUS_FAIL';

export const CREATE_LEADDETAIL_LOAD = 'leadHistory/CREATE_LEADDETAIL_LOAD';
export const CREATE_LEADDETAIL_SUCCESS = 'leadHistory/CREATE_LEADDETAIL_SUCCESS';
export const CREATE_LEADDETAIL_FAIL = 'leadHistory/CREATE_LEADDETAIL_FAIL';

export const LOST_REASON_LOAD = 'leadHistory/LOST_REASON_LOAD';
export const LOST_REASON_SUCCESS = 'leadHistory/LOST_REASON_SUCCESS';
export const LOST_REASON_FAILURE = 'leadHistory/LOST_REASON_FAILURE';

export const LEAD_FOLLOW_UP_LOAD = 'leadHistory/LEAD_FOLLOW_UP_LOAD';
export const LEAD_FOLLOW_UP_SUCCESS = 'leadHistory/LEAD_FOLLOW_UP_SUCCESS';
export const LEAD_FOLLOW_UP_FAILURE = 'leadHistory/LEAD_FOLLOW_UP_FAILURE';

export const UPDATE_LEAD_FOLLOW_LOAD = 'leadHistory/UPDATE_LEAD_FOLLOW_LOAD';
export const UPDATE_LEAD_FOLLOW_SUCCESS = 'leadHistory/UPDATE_LEAD_FOLLOW_SUCCESS';
export const UPDATE_LEAD_FOLLOW_FAILURE = 'leadHistory/UPDATE_LEAD_FOLLOW_FAILURE';

export const ACTION_COMMENT_LOAD = 'leadHistory/ACTION_COMMENT_LOAD';
export const ACTION_COMMENT_SUCCESS = 'leadHistory/ACTION_COMMENT_SUCCESS';
export const ACTION_COMMENT_FAILURE = 'leadHistory/ACTION_COMMENT_FAILURE';

export const LEAD_ACTIVITIES_LOAD = 'leadHistory/LEAD_ACTIVITIES_LOAD';
export const LEAD_ACTIVITIES_SUCCESS = 'leadHistory/LEAD_ACTIVITIES_SUCCESS';
export const LEAD_ACTIVITIES_FAILURE = 'leadHistory/LEAD_ACTIVITIES_FAILURE';

export const LEAD_LOST_LOAD = 'leadHistory/LEAD_LOST_LOAD';
export const LEAD_LOST_SUCCESS = 'leadHistory/LEAD_LOST_SUCCESS';
export const LEAD_LOST_FAILURE = 'leadHistory/LEAD_LOST_FAILURE';

export const CLEAR_LEAD_ACTIVITIES = 'leadHistory/CLEAR_LEAD_ACTIVITIES';
