export const FINANCIER_INFO_LOAD = 'financier/FINANCIER_INFO_LOAD';
export const FINANCIER_INFO_SUCCESS = 'financier/FINANCIER_INFO_SUCCESS';
export const FINANCIER_INFO_FAIL = 'financier/FINANCIER_INFO_FAIL';

export const UPDATEFINANCIER_INFO_LOAD = 'financier/UPDATEFINANCIER_INFO_LOAD';
export const UPDATEFINANCIER_INFO_SUCCESS = 'financier/UPDATEFINANCIER_INFO_SUCCESS';
export const UPDATEFINANCIER_INFO_FAIL = 'financier/UPDATEFINANCIER_INFO_FAIL';

export const UPDATEUSERINFO_INFO_LOAD = 'financier/UPDATEUSERINFO_INFO_LOAD';
export const UPDATEUSERINFO_INFO_SUCCESS = 'financier/UPDATEUSERINFO_INFO_SUCCESS';
export const UPDATEUSERINFO_INFO_FAIL = 'financier/UPDATEUSERINFO_INFO_FAIL';
