export const LOAD_DEALERSHIP_DETAIL = 'dealershipDetails/LOAD_DEALERSHIP_DETAIL';
export const LOAD_DEALERSHIP_DETAIL_SUCCESS = 'dealershipDetails/LOAD_DEALERSHIP_DETAIL_SUCCESS';
export const LOAD_DEALERSHIP_DETAIL_FAIL = 'dealershipDetails/LOAD_DEALERSHIP_DETAIL_FAIL';
