export const GETMANUFACTURERID_LOAD = 'getVehicles/GETMANUFACTURERID_LOAD';
export const GETMANUFACTURERID_SUCCESS = 'getVehicles/GETMANUFACTURERID_SUCCESS';
export const GETMANUFACTURERID_FAIL = 'getVehicles/GETMANUFACTURERID_FAIL';

export const GETVEHICLES_LOAD = 'getVehicles/GETVEHICLES_LOAD';
export const GETVEHICLES_SUCCESS = 'getVehicles/GETVEHICLES_SUCCESS';
export const GETVEHICLES_FAIL = 'getVehicles/GETVEHICLES_FAIL';

export const UPDATE_VEHICLEPREFERED_LOAD = 'getVehicles/UPDATE_VEHICLEPREFERED_LOAD';
export const UPDATE_VEHICLEPREFERED_SUCCESS = 'getVehicles/UPDATE_VEHICLEPREFERED_SUCCESS';
export const UPDATE_VEHICLEPREFERED_FAIL = 'getVehicles/UPDATE_VEHICLEPREFERED_FAIL';
