export const GET_FIANANCIERLIST_LOAD = 'financierListing/GET_FIANANCIERLIST_LOAD';
export const GET_FIANANCIERLIST_SUCCESS = 'financierListing/GET_FIANANCIERLIST_SUCCESS';
export const GET_FIANANCIERLIST_FAIL = 'financierListing/GET_FIANANCIERLIST_FAIL';

export const GET_FIANANCIER_REP_LIST_LOAD = 'financierListing/GET_FIANANCIER_REP_LIST_LOAD';
export const GET_FIANANCIER_REP_LIST_SUCCESS = 'financierListing/GET_FIANANCIER_REP_LIST_SUCCESS';
export const GET_FIANANCIER_REP_LIST_FAIL = 'financierListing/GET_FIANANCIER_REP_LIST_FAIL';

export const CREATE_FIANANCIER_LEAD_LOAD = 'financierListing/CREATE_FIANANCIER_LEAD_LOAD';
export const CREATE_FIANANCIER_LEAD_SUCCESS = 'financierListing/CREATE_FIANANCIER_LEAD_SUCCESS';
export const CREATE_FIANANCIER_LEAD_FAIL = 'financierListing/CREATE_FIANANCIER_LEAD_FAIL';

export const UPDATE_FIANANCIER_LEAD_LOAD = 'financierListing/UPDATE_FIANANCIER_LEAD_LOAD';
export const UPDATE_FIANANCIER_LEAD_SUCCESS = 'financierListing/UPDATE_FIANANCIER_LEAD_SUCCESS';
export const UPDATE_FIANANCIER_LEAD_FAIL = 'financierListing/UPDATE_FIANANCIER_LEAD_FAIL';

export const GET_FINANCIER_LEAD_LOAD = 'financierListing/GET_FINANCIER_LEAD_LOAD';
export const GET_FINANCIER_LEAD_SUCCESS = 'financierListing/GET_FINANCIER_LEAD_SUCCESS';
export const GET_FINANCIER_LEAD_FAIL = 'financierListing/GET_FINANCIER_LEAD_FAIL';

