export const LOAD_PRODUCT_SUMMARY = 'myDealership/LOAD_PRODUCT_SUMMARY';
export const LOAD_PRODUCT_SUMMARY_SUCCESS = 'myDealership/LOAD_PRODUCT_SUMMARY_SUCCESS';
export const LOAD_PRODUCT_SUMMARY_FAIL = 'myDealership/LOAD_PRODUCT_SUMMARY_FAIL';

export const LOAD_PRODUCTS = 'myDealership/LOAD_PRODUCTS_LOAD';
export const LOAD_PRODUCTS_SUCCESS = 'myDealership/LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_FAIL = 'myDealership/LOAD_PRODUCTS_FAIL';

export const UPDATE_DEALERSHIP_LOAD = 'myDealership/UPDATE_DEALERSHIP_LOAD';
export const UPDATE_DEALERSHIP_SUCCESS = 'myDealership/UPDATE_DEALERSHIP_SUCCESS';
export const UPDATE_DEALERSHIP_FAIL = 'myDealership/UPDATE_DEALERSHIP_FAIL';

export const SEND_LEADREPORT_LOAD = 'myDealership/SEND_LEADREPORT_LOAD';
export const SEND_LEADREPORT_SUCCESS = 'myDealership/SEND_LEADREPORT_SUCCESS';
export const SEND_LEADREPORT_FAIL = 'myDealership/SEND_LEADREPORT_FAIL';
