export const GETVEHICLEACCESORIES_LOAD = 'vehicleAccessories/GETVEHICLEACCESORIES_LOAD';
export const GETVEHICLEACCESORIES_SUCCESS = 'vehicleAccessories/GETVEHICLEACCESORIES_SUCCESS';
export const GETVEHICLEACCESORIES_FAIL = 'vehicleAccessories/GETVEHICLEACCESORIES_FAIL';

export const SAVEVEHICLEACCESORIES_LOAD = 'vehicleAccessories/SAVEVEHICLEACCESORIES_LOAD';
export const SAVEVEHICLEACCESORIES_SUCCESS = 'vehicleAccessories/SAVEVEHICLEACCESORIES_SUCCESS';
export const SAVEVEHICLEACCESORIES_FAIL = 'vehicleAccessories/SAVEVEHICLEACCESORIES_FAIL';
