export const INVENTORY_INFO_LOAD = 'inventory/INVENTORY_INFO_LOAD';
export const INVENTORY_INFO_SUCCESS = 'inventory/INVENTORY_INFO_SUCCESS';
export const INVENTORY_INFO_FAIL = 'inventory/INVENTORY_INFO_FAIL';

export const VARIANT_INFO_LOAD = 'inventory/VARIANT_INFO_LOAD';
export const VARIANT_INFO_SUCCESS = 'inventory/VARIANT_INFO_SUCCESS';
export const VARIANT_INFO_FAIL = 'inventory/VARIANT_INFO_FAIL';

export const VARIANTPRICE_INFO_LOAD = 'inventory/VARIANTPRICE_INFO_LOAD';
export const VARIANTPRICE_INFO_SUCCESS = 'inventory/VARIANTPRICE_INFO_SUCCESS';
export const VARIANTPRICE_INFO_FAIL = 'inventory/VARIANTPRICE_INFO_FAIL';

export const CLEAR_VARIANT_DETAILS = 'inventory/CLEAR_VARIANT_DETAILS';
export const CLEAR_INVENTORY_LIST = 'inventory/CLEAR_INVENTORY_LIST';

export const UPDATEVARIANTPRICE_INFO_LOAD = 'inventory/UPDATEVARIANTPRICE_INFO_LOAD';
export const UPDATEVARIANTPRICE_INFO_SUCCESS = 'inventory/UPDATEVARIANTPRICE_INFO_SUCCESS';
export const UPDATEVARIANTPRICE_INFO_FAIL = 'inventory/UPDATEVARIANTPRICE_INFO_FAIL';

export const VARIANTSTOCK_INFO_LOAD = 'inventory/VARIANTSTOCK_INFO_LOAD';
export const VARIANTSTOCK_INFO_SUCCESS = 'inventory/VARIANTSTOCK_INFO_SUCCESS';
export const VARIANTSTOCK_INFO_FAIL = 'inventory/VARIANTSTOCK_INFO_FAIL';

export const UPDATEVARIANTSTOCK_INFO_LOAD = 'inventory/UPDATEVARIANTSTOCK_INFO_LOAD';
export const UPDATEVARIANTSTOCK_INFO_SUCCESS = 'inventory/UPDATEVARIANTSTOCK_INFO_SUCCESS';
export const UPDATEVARIANTSTOCK_INFO_FAIL = 'inventory/UPDATEVARIANTSTOCK_INFO_FAIL';

export const INCENTIVEOFFER_INFO_LOAD = 'inventory/INCENTIVEOFFER_INFO_LOAD';
export const INCENTIVEOFFER_INFO_SUCCESS = 'inventory/INCENTIVEOFFER_INFO_SUCCESS';
export const INCENTIVEOFFER_INFO_FAIL = 'inventory/INCENTIVEOFFER_INFO_FAIL';

export const UPDATE_INCENTIVEOFFER_INFO_LOAD = 'inventory/UPDATE_INCENTIVEOFFER_INFO_LOAD';
export const UPDATE_INCENTIVEOFFER_INFO_SUCCESS = 'inventory/UPDATE_INCENTIVEOFFER_INFO_SUCCESS';
export const UDPATE_INCENTIVEOFFER_INFO_FAIL = 'inventory/UDPATE_INCENTIVEOFFER_INFO_FAIL';

export const GETINSURANCEPRICE_INFO_LOAD = 'inventory/GETINSURANCEPRICE_INFO_LOAD';
export const GETINSURANCEPRICE_INFO_SUCCESS = 'inventory/GETINSURANCEPRICE_INFO_SUCCESS';
export const GETINSURANCEPRICE_INFO_FAIL = 'inventory/GETINSURANCEPRICE_INFO_FAIL';

export const UPDATEINSURANCEPRICE_INFO_LOAD = 'inventory/UPDATEINSURANCEPRICE_INFO_LOAD';
export const UPDATEINSURANCEPRICE_INFO_SUCCESS = 'inventory/UPDATEINSURANCEPRICE_INFO_SUCCESS';
export const UPDATEINSURANCEPRICE_INFO_FAIL = 'inventory/UPDATEINSURANCEPRICE_INFO_FAIL';

