export const DEALER_DETAILS_LOAD = 'onboarding/DEALER_DETAILS_LOAD';
export const DEALER_DETAILS_SUCCESS = 'onboarding/DEALER_DETAILS_SUCCESS';
export const DEALER_DETAILS_FAIL = 'onboarding/DEALER_DETAILS_FAIL';

export const SAVE_DEALERSHIP_LOAD = 'onboarding/SAVE_DEALERSHIP_LOAD';
export const SAVE_DEALERSHIP_SUCCESS = 'onboarding/SAVE_DEALERSHIP_SUCCESS';
export const SAVE_DEALERSHIP_FAIL = 'onboarding/SAVE_DEALERSHIP_FAIL';
